Traceback (most recent call last):
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\samuel\miniconda3\envs\tensorflow\lib\site-packages\nbclient\client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# np.max(a) prints the maximum value in 'a'.
print(f'Maximum value in X_train is',np.max(X_train))

# Convert into greyscale
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-6-f02e31240434>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# np.max(a) prints the maximum value in 'a'.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mprint[0m[1;33m([0m[1;34mf'Maximum value in X_train is'[0m[1;33m,[0m[0mnp[0m[1;33m.[0m[0mmax[0m[1;33m([0m[0mX_train[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [1;33m[0m[0m
[0;32m      4[0m [1;31m# Convert into greyscale[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mX_train[0m [1;33m=[0m [0mX_train[0m[1;33m.[0m[0mastype[0m[1;33m([0m[1;34m'float32'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

